# Generated by Django 5.2.14 on 2026-05-29 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Эмодзи/иконка')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('type', models.CharField(choices=[('cottage', 'Коттедж'), ('dacha', 'Дача'), ('banya', 'Баня/сауна'), ('glamping', 'Глэмпинг'), ('zone', 'Зона отдыха')], default='cottage', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('suspended', 'Снято')], default='draft', max_length=20, verbose_name='Статус')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Область')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город/посёлок')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Комнат')),
                ('beds', models.PositiveSmallIntegerField(default=1, verbose_name='Спальных мест')),
                ('max_guests', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. гостей')),
                ('area_sqm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Площадь, м²')),
                ('base_price', models.PositiveIntegerField(default=0, verbose_name='Цена за сутки, ₸')),
                ('weekend_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена за выходные, ₸')),
                ('cleaning_fee', models.PositiveIntegerField(default=0, verbose_name='Уборка, ₸')),
                ('min_nights', models.PositiveSmallIntegerField(default=1, verbose_name='Мин. ночей')),
                ('instant_booking', models.BooleanField(default=False, verbose_name='Мгновенное бронирование')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='listings.amenity', verbose_name='Удобства')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Хост')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='С')),
                ('end_date', models.DateField(verbose_name='По (выезд)')),
                ('reason', models.CharField(blank=True, default='Закрыто хостом', max_length=100, verbose_name='Причина')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='listings.property')),
            ],
            options={
                'verbose_name': 'Блокировка дат',
                'verbose_name_plural': 'Блокировки дат',
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.property')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
