# Generated by Django 5.2.14 on 2026-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cancellation_policy',
            field=models.CharField(choices=[('flexible', 'Гибкая'), ('moderate', 'Умеренная'), ('strict', 'Строгая')], default='flexible', max_length=10, verbose_name='Политика отмены'),
        ),
    ]
