# Generated by Django 5.2.14 on 2026-05-29 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Заезд')),
                ('check_out', models.DateField(verbose_name='Выезд')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, verbose_name='Гостей')),
                ('status', models.CharField(choices=[('pending_payment', 'Ждёт оплаты'), ('pending_host', 'Ждёт подтверждения хоста'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='pending_payment', max_length=20)),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('base_amount', models.PositiveIntegerField(default=0, verbose_name='Проживание, ₸')),
                ('cleaning_fee', models.PositiveIntegerField(default=0, verbose_name='Уборка, ₸')),
                ('service_fee', models.PositiveIntegerField(default=0, verbose_name='Сервисный сбор, ₸')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Итого к оплате, ₸')),
                ('host_payout', models.PositiveIntegerField(default=0, verbose_name='К выплате хосту, ₸')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='listings.property')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='checkout_after_checkin')],
            },
        ),
    ]
